using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShimmerChatLib.Tool
{
    public interface ITool
    {
		/// <summary>
		/// Executes a chat operation using the specified input, chat context, and agent, and returns the result as an
		/// asynchronous operation.
		/// </summary>
		/// <param name="input">The input message or prompt to process. Cannot be null.</param>
		/// <param name="chat">The chat context to use for the operation. If null, a test env may be used.</param>
		/// <param name="agent">The agent to use for processing the input. If null, a test env may be used.</param>
		/// <returns>A task that represents the asynchronous operation. The task result contains the response generated by the
		/// chat agent.</returns>
		public Task<string> Execute(string input, Chat? chat, Agent? agent);
        public SharperLLM.FunctionCalling.Tool GetToolDefinition();
    }
}
